// This file is auto-generated by sync-engine.mjs. Do not edit manually.
import dynamic from 'next/dynamic';

import * as utils_v1 from './v1/utils';
import * as utils_v2 from './v2/utils';

export const EngineUtilsRegistry = {
  v1: utils_v1,
  v2: utils_v2,
};

export const EngineComponentsRegistry = {
  v1: {
    Renderer: dynamic(() => import('./v1/renderer')),
    InsertModal: dynamic(() => import('./v1/modals').then(m => m.InsertModal)),
    UpdateModal: dynamic(() => import('./v1/modals').then(m => m.UpdateModal)),
  },
  v2: {
    Renderer: dynamic(() => import('./v2/renderer')),
    InsertModal: dynamic(() => import('./v2/modals').then(m => m.InsertModal)),
    UpdateModal: dynamic(() => import('./v2/modals').then(m => m.UpdateModal)),
  },
};
